spring:
  application:
    name: auth-resource-demo
server:
  port: 8001
  session:
    cookie:
       name: OAUTH_SESSIONID_DEMO1

security:
  oauth2:
    client:
      client-id: clientId1
      client-secret: secret1
      access-token-uri: http://localhost:80/oauth/token
      user-authorization-uri: http://localhost:80/oauth/authorize
      #当使用jwt 对称加密的形式的时候加下面的配置
    resource:
      jwt:
        key-value:  zfh
        key-uri: http://localhost:80/oauth/token_key   #解析jwt令牌所需要密钥的地址
      user-info-uri: http://localhost:80/user/me


login.url: http://www.zfh.com/login

#auth
#server.session.cookie.name : OAUTH2SESSION
#security.oauth2.client.client-id: zfh1
#security.oauth2.client.client-secret: zfh
#security.oauth2.client.access-token-uri: http://localhost:8003/oauth/token
#security.oauth2.client.user-authorization-uri: http://localhost:8003/oauth/authorize
#security.oauth2.client.client-authentication-scheme: query
#logging.level.root: info