spring:
  application:
    name: auth-resource-demo
server:
  port: 8000
  session:
      cookie:
         name: OAUTH_SESSIONID_DEMO
security:
  oauth2:
    client:
      client-id: clientId
      client-secret: secret
      access-token-uri: http://localhost/oauth/token
      user-authorization-uri: http://localhost/oauth/authorize
      #当使用jwt 对称加密的形式的时候加下面的配置
    resource:
      jwt:
        #key-value: zfh
        key-value:  "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCCBc8g0H1PoyOmW42057eA1ynBVv781m0hz++AesxX3zWGZzb3ZC6qSq3X6h8MFkc6V5PnWCgyaMKta1bdU1iMmL2rI8lLulWCoU808/P/XgHbB1Vnu4EQquapl0EWWM2XVs/vgABZXwnp7e2bDDnq+DeZFwntTAsH2l78deDupQIDAQAB\n-----END PUBLIC KEY-----"
      user-info-uri: http://localhost/user/me


login.url: http://www.zfh.com/login

#auth
#server.session.cookie.name : OAUTH2SESSION
#security.oauth2.client.client-id: zfh1
#security.oauth2.client.client-secret: zfh
#security.oauth2.client.access-token-uri: http://localhost:8003/oauth/token
#security.oauth2.client.user-authorization-uri: http://localhost:8003/oauth/authorize
#security.oauth2.client.client-authentication-scheme: query
#logging.level.root: info